//-----------------------------------------------------------------------------
// <auto-generated> 
//   This code was generated by a tool. 
// 
//   Changes to this file may cause incorrect behavior and will be lost if  
//   the code is regenerated.
//
//   Tool: AllJoynCodeGenerator.exe
//
//   This tool is located in the Windows 10 SDK and the Windows 10 AllJoyn 
//   Visual Studio Extension in the Visual Studio Gallery.  
//
//   The generated code should be packaged in a Windows 10 C++/CX Runtime  
//   Component which can be consumed in any UWP-supported language using 
//   APIs that are available in Windows.Devices.AllJoyn.
//
//   Using AllJoynCodeGenerator - Invoke the following command with a valid 
//   Introspection XML file and a writable output directory:
//     AllJoynCodeGenerator -i <INPUT XML FILE> -o <OUTPUT DIRECTORY>
// </auto-generated>
//-----------------------------------------------------------------------------
#pragma once

using namespace concurrency;

namespace org { namespace allseen { namespace LSF { namespace LampParameters {

ref class LampParametersConsumer;

public ref class LampParametersJoinSessionResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    property LampParametersConsumer^ Consumer
    {
        LampParametersConsumer^ get() { return m_consumer; }
    internal:
        void set(_In_ LampParametersConsumer^ value) { m_consumer = value; }
    };

private:
    int32 m_status;
    LampParametersConsumer^ m_consumer;
};

public ref class LampParametersGetVersionResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    property uint32 Version
    {
        uint32 get() { return m_value; }
    internal:
        void set(_In_ uint32 value) { m_value = value; }
    }

    static LampParametersGetVersionResult^ CreateSuccessResult(_In_ uint32 value)
    {
        auto result = ref new LampParametersGetVersionResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        result->Version = value;
        result->m_creationContext = Concurrency::task_continuation_context::use_current();
        return result;
    }

    static LampParametersGetVersionResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new LampParametersGetVersionResult();
        result->Status = status;
        return result;
    }
internal:
    Concurrency::task_continuation_context m_creationContext = Concurrency::task_continuation_context::use_default();

private:
    int32 m_status;
    uint32 m_value;
};

public ref class LampParametersGetEnergy_Usage_MilliwattsResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    property uint32 Energy_Usage_Milliwatts
    {
        uint32 get() { return m_value; }
    internal:
        void set(_In_ uint32 value) { m_value = value; }
    }

    static LampParametersGetEnergy_Usage_MilliwattsResult^ CreateSuccessResult(_In_ uint32 value)
    {
        auto result = ref new LampParametersGetEnergy_Usage_MilliwattsResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        result->Energy_Usage_Milliwatts = value;
        result->m_creationContext = Concurrency::task_continuation_context::use_current();
        return result;
    }

    static LampParametersGetEnergy_Usage_MilliwattsResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new LampParametersGetEnergy_Usage_MilliwattsResult();
        result->Status = status;
        return result;
    }
internal:
    Concurrency::task_continuation_context m_creationContext = Concurrency::task_continuation_context::use_default();

private:
    int32 m_status;
    uint32 m_value;
};

public ref class LampParametersGetBrightness_LumensResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    property uint32 Brightness_Lumens
    {
        uint32 get() { return m_value; }
    internal:
        void set(_In_ uint32 value) { m_value = value; }
    }

    static LampParametersGetBrightness_LumensResult^ CreateSuccessResult(_In_ uint32 value)
    {
        auto result = ref new LampParametersGetBrightness_LumensResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        result->Brightness_Lumens = value;
        result->m_creationContext = Concurrency::task_continuation_context::use_current();
        return result;
    }

    static LampParametersGetBrightness_LumensResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new LampParametersGetBrightness_LumensResult();
        result->Status = status;
        return result;
    }
internal:
    Concurrency::task_continuation_context m_creationContext = Concurrency::task_continuation_context::use_default();

private:
    int32 m_status;
    uint32 m_value;
};

} } } } 
