//-----------------------------------------------------------------------------
// <auto-generated> 
//   This code was generated by a tool. 
// 
//   Changes to this file may cause incorrect behavior and will be lost if  
//   the code is regenerated.
//
//   Tool: AllJoynCodeGenerator.exe
//
//   This tool is located in the Windows 10 SDK and the Windows 10 AllJoyn 
//   Visual Studio Extension in the Visual Studio Gallery.  
//
//   The generated code should be packaged in a Windows 10 C++/CX Runtime  
//   Component which can be consumed in any UWP-supported language using 
//   APIs that are available in Windows.Devices.AllJoyn.
//
//   Using AllJoynCodeGenerator - Invoke the following command with a valid 
//   Introspection XML file and a writable output directory:
//     AllJoynCodeGenerator -i <INPUT XML FILE> -o <OUTPUT DIRECTORY>
// </auto-generated>
//-----------------------------------------------------------------------------
#pragma once

using namespace concurrency;

namespace com { namespace dotMorten { namespace PhilipsHueDSB { namespace PhilipsHue {

ref class PhilipsHueConsumer;

public ref class PhilipsHueJoinSessionResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    property PhilipsHueConsumer^ Consumer
    {
        PhilipsHueConsumer^ get() { return m_consumer; }
    internal:
        void set(_In_ PhilipsHueConsumer^ value) { m_consumer = value; }
    };

private:
    int32 m_status;
    PhilipsHueConsumer^ m_consumer;
};

public ref class PhilipsHueGetIsLinkedResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    property bool IsLinked
    {
        bool get() { return m_value; }
    internal:
        void set(_In_ bool value) { m_value = value; }
    }

    static PhilipsHueGetIsLinkedResult^ CreateSuccessResult(_In_ bool value)
    {
        auto result = ref new PhilipsHueGetIsLinkedResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        result->IsLinked = value;
        result->m_creationContext = Concurrency::task_continuation_context::use_current();
        return result;
    }

    static PhilipsHueGetIsLinkedResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new PhilipsHueGetIsLinkedResult();
        result->Status = status;
        return result;
    }
internal:
    Concurrency::task_continuation_context m_creationContext = Concurrency::task_continuation_context::use_default();

private:
    int32 m_status;
    bool m_value;
};

} } } } 
