//-----------------------------------------------------------------------------
// <auto-generated> 
//   This code was generated by a tool. 
// 
//   Changes to this file may cause incorrect behavior and will be lost if  
//   the code is regenerated.
//
//   Tool: AllJoynCodeGenerator.exe
//
//   This tool is located in the Windows 10 SDK and the Windows 10 AllJoyn 
//   Visual Studio Extension in the Visual Studio Gallery.  
//
//   The generated code should be packaged in a Windows 10 C++/CX Runtime  
//   Component which can be consumed in any UWP-supported language using 
//   APIs that are available in Windows.Devices.AllJoyn.
//
//   Using AllJoynCodeGenerator - Invoke the following command with a valid 
//   Introspection XML file and a writable output directory:
//     AllJoynCodeGenerator -i <INPUT XML FILE> -o <OUTPUT DIRECTORY>
// </auto-generated>
//-----------------------------------------------------------------------------
#pragma once

namespace com { namespace dotMorten { namespace PhilipsHueDSB { namespace PhilipsHue {

// This class, and the associated EventArgs classes, exist for the benefit of JavaScript developers who
// do not have the ability to implement IPhilipsHueService. Instead, PhilipsHueServiceEventAdapter
// provides the Interface implementation and exposes a set of compatible events to the developer.
public ref class PhilipsHueServiceEventAdapter sealed : [Windows::Foundation::Metadata::Default] IPhilipsHueService
{
public:
    // Method Invocation Events
    // Property Read Events
    event Windows::Foundation::TypedEventHandler<PhilipsHueServiceEventAdapter^, PhilipsHueGetIsLinkedRequestedEventArgs^>^ GetIsLinkedRequested 
    { 
        Windows::Foundation::EventRegistrationToken add(Windows::Foundation::TypedEventHandler<PhilipsHueServiceEventAdapter^, PhilipsHueGetIsLinkedRequestedEventArgs^>^ handler) 
        { 
            return _GetIsLinkedRequested += ref new Windows::Foundation::EventHandler<Platform::Object^>
            ([handler](Platform::Object^ sender, Platform::Object^ args)
            {
                handler->Invoke(safe_cast<PhilipsHueServiceEventAdapter^>(sender), safe_cast<PhilipsHueGetIsLinkedRequestedEventArgs^>(args));
            }, Platform::CallbackContext::Same);
        } 
        void remove(Windows::Foundation::EventRegistrationToken token) 
        { 
            _GetIsLinkedRequested -= token; 
        } 
    internal: 
        void raise(PhilipsHueServiceEventAdapter^ sender, PhilipsHueGetIsLinkedRequestedEventArgs^ args) 
        { 
            _GetIsLinkedRequested(sender, args);
        } 
    }

    // Property Write Events
    // IPhilipsHueService Implementation

    virtual Windows::Foundation::IAsyncOperation<PhilipsHueGetIsLinkedResult^>^ GetIsLinkedAsync(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info);


private:
    event Windows::Foundation::EventHandler<Platform::Object^>^ _GetIsLinkedRequested;
};

} } } } 
