//-----------------------------------------------------------------------------
// <auto-generated> 
//   This code was generated by a tool. 
// 
//   Changes to this file may cause incorrect behavior and will be lost if  
//   the code is regenerated.
//
//   Tool: AllJoynCodeGenerator.exe
//
//   This tool is located in the Windows 10 SDK and the Windows 10 AllJoyn 
//   Visual Studio Extension in the Visual Studio Gallery.  
//
//   The generated code should be packaged in a Windows 10 C++/CX Runtime  
//   Component which can be consumed in any UWP-supported language using 
//   APIs that are available in Windows.Devices.AllJoyn.
//
//   Using AllJoynCodeGenerator - Invoke the following command with a valid 
//   Introspection XML file and a writable output directory:
//     AllJoynCodeGenerator -i <INPUT XML FILE> -o <OUTPUT DIRECTORY>
// </auto-generated>
//-----------------------------------------------------------------------------
#pragma once

namespace com { namespace dotMorten { namespace PhilipsHueDSB { namespace PhilipsHue { namespace MainInterface {

// This class, and the associated EventArgs classes, exist for the benefit of JavaScript developers who
// do not have the ability to implement IMainInterfaceService. Instead, MainInterfaceServiceEventAdapter
// provides the Interface implementation and exposes a set of compatible events to the developer.
public ref class MainInterfaceServiceEventAdapter sealed : [Windows::Foundation::Metadata::Default] IMainInterfaceService
{
public:
    // Method Invocation Events
    event Windows::Foundation::TypedEventHandler<MainInterfaceServiceEventAdapter^, MainInterfaceLinkCalledEventArgs^>^ LinkCalled 
    { 
        Windows::Foundation::EventRegistrationToken add(Windows::Foundation::TypedEventHandler<MainInterfaceServiceEventAdapter^, MainInterfaceLinkCalledEventArgs^>^ handler) 
        { 
            return _LinkCalled += ref new Windows::Foundation::EventHandler<Platform::Object^>
            ([handler](Platform::Object^ sender, Platform::Object^ args)
            {
                handler->Invoke(safe_cast<MainInterfaceServiceEventAdapter^>(sender), safe_cast<MainInterfaceLinkCalledEventArgs^>(args));
            }, Platform::CallbackContext::Same);
        } 
        void remove(Windows::Foundation::EventRegistrationToken token) 
        { 
            _LinkCalled -= token; 
        } 
    internal: 
        void raise(MainInterfaceServiceEventAdapter^ sender, MainInterfaceLinkCalledEventArgs^ args) 
        { 
            _LinkCalled(sender, args);
        } 
    }

    // Property Read Events
    // Property Write Events
    // IMainInterfaceService Implementation
    virtual Windows::Foundation::IAsyncOperation<MainInterfaceLinkResult^>^ LinkAsync(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info);



private:
    event Windows::Foundation::EventHandler<Platform::Object^>^ _LinkCalled;
};

} } } } } 
