
//-----------------------------------------------------------------------------
// <auto-generated> 
//   This code was generated by a tool. 
// 
//   Changes to this file may cause incorrect behavior and will be lost if  
//   the code is regenerated.
//
//   Tool: AllJoynCodeGenerator.exe
//
//   This tool is located in the Windows 10 SDK and the Windows 10 AllJoyn 
//   Visual Studio Extension in the Visual Studio Gallery.  
//
//   The generated code should be packaged in a Windows 10 C++/CX Runtime  
//   Component which can be consumed in any UWP-supported language using 
//   APIs that are available in Windows.Devices.AllJoyn.
//
//   Using AllJoynCodeGenerator - Invoke the following command with a valid 
//   Introspection XML file and a writable output directory:
//     AllJoynCodeGenerator -i <INPUT XML FILE> -o <OUTPUT DIRECTORY>
// </auto-generated>
//-----------------------------------------------------------------------------
#pragma once

#include <windows.h>
#include <ppltasks.h>
#include <concrt.h>
#include <collection.h>
#include <windows.devices.alljoyn.interop.h>
#include <map>

#include <alljoyn_c/busattachment.h>
#include <alljoyn_c/dbusstddefines.h>
#include <alljoyn_c/AboutData.h>
#include <alljoyn_c/AboutObj.h>
#include <alljoyn_c/AboutObjectDescription.h>

#include "AllJoynHelpers.h"
#include "AllJoynBusObjectManager.h"

#define PROJECT_NAMESPACE org::allseen::LSF

#include "Structures.h"
#include "TypeConversionHelpers.h"

#include "LampDetails/LampDetailsMethodResults.h"
#include "LampDetails/LampDetailsEventArgs.h"
#include "LampDetails/ILampDetailsService.h"
#include "LampDetails/LampDetailsSignals.h"
#include "LampDetails/LampDetailsProducer.h"
#include "LampDetails/LampDetailsWatcher.h"
#include "LampDetails/LampDetailsConsumer.h"
#include "LampDetails/LampDetailsServiceEventArgs.h"
#include "LampDetails/LampDetailsServiceEventAdapter.h"

#include "LampParameters/LampParametersMethodResults.h"
#include "LampParameters/LampParametersEventArgs.h"
#include "LampParameters/ILampParametersService.h"
#include "LampParameters/LampParametersSignals.h"
#include "LampParameters/LampParametersProducer.h"
#include "LampParameters/LampParametersWatcher.h"
#include "LampParameters/LampParametersConsumer.h"
#include "LampParameters/LampParametersServiceEventArgs.h"
#include "LampParameters/LampParametersServiceEventAdapter.h"

#include "LampService/LampServiceMethodResults.h"
#include "LampService/LampServiceEventArgs.h"
#include "LampService/ILampServiceService.h"
#include "LampService/LampServiceSignals.h"
#include "LampService/LampServiceProducer.h"
#include "LampService/LampServiceWatcher.h"
#include "LampService/LampServiceConsumer.h"
#include "LampService/LampServiceServiceEventArgs.h"
#include "LampService/LampServiceServiceEventAdapter.h"

#include "LampState/LampStateMethodResults.h"
#include "LampState/LampStateEventArgs.h"
#include "LampState/ILampStateService.h"
#include "LampState/LampStateSignals.h"
#include "LampState/LampStateProducer.h"
#include "LampState/LampStateWatcher.h"
#include "LampState/LampStateConsumer.h"
#include "LampState/LampStateServiceEventArgs.h"
#include "LampState/LampStateServiceEventAdapter.h"


