//-----------------------------------------------------------------------------
// <auto-generated> 
//   This code was generated by a tool. 
// 
//   Changes to this file may cause incorrect behavior and will be lost if  
//   the code is regenerated.
//
//   Tool: AllJoynCodeGenerator.exe
//
//   This tool is located in the Windows 10 SDK and the Windows 10 AllJoyn 
//   Visual Studio Extension in the Visual Studio Gallery.  
//
//   The generated code should be packaged in a Windows 10 C++/CX Runtime  
//   Component which can be consumed in any UWP-supported language using 
//   APIs that are available in Windows.Devices.AllJoyn.
//
//   Using AllJoynCodeGenerator - Invoke the following command with a valid 
//   Introspection XML file and a writable output directory:
//     AllJoynCodeGenerator -i <INPUT XML FILE> -o <OUTPUT DIRECTORY>
// </auto-generated>
//-----------------------------------------------------------------------------
#pragma once

using namespace concurrency;

namespace org { namespace allseen { namespace LSF { namespace LampDetails {

ref class LampDetailsConsumer;

public ref class LampDetailsJoinSessionResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    property LampDetailsConsumer^ Consumer
    {
        LampDetailsConsumer^ get() { return m_consumer; }
    internal:
        void set(_In_ LampDetailsConsumer^ value) { m_consumer = value; }
    };

private:
    int32 m_status;
    LampDetailsConsumer^ m_consumer;
};

public ref class LampDetailsGetVersionResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    property uint32 Version
    {
        uint32 get() { return m_value; }
    internal:
        void set(_In_ uint32 value) { m_value = value; }
    }

    static LampDetailsGetVersionResult^ CreateSuccessResult(_In_ uint32 value)
    {
        auto result = ref new LampDetailsGetVersionResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        result->Version = value;
        result->m_creationContext = Concurrency::task_continuation_context::use_current();
        return result;
    }

    static LampDetailsGetVersionResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new LampDetailsGetVersionResult();
        result->Status = status;
        return result;
    }
internal:
    Concurrency::task_continuation_context m_creationContext = Concurrency::task_continuation_context::use_default();

private:
    int32 m_status;
    uint32 m_value;
};

public ref class LampDetailsGetMakeResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    property uint32 Make
    {
        uint32 get() { return m_value; }
    internal:
        void set(_In_ uint32 value) { m_value = value; }
    }

    static LampDetailsGetMakeResult^ CreateSuccessResult(_In_ uint32 value)
    {
        auto result = ref new LampDetailsGetMakeResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        result->Make = value;
        result->m_creationContext = Concurrency::task_continuation_context::use_current();
        return result;
    }

    static LampDetailsGetMakeResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new LampDetailsGetMakeResult();
        result->Status = status;
        return result;
    }
internal:
    Concurrency::task_continuation_context m_creationContext = Concurrency::task_continuation_context::use_default();

private:
    int32 m_status;
    uint32 m_value;
};

public ref class LampDetailsGetModelResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    property uint32 Model
    {
        uint32 get() { return m_value; }
    internal:
        void set(_In_ uint32 value) { m_value = value; }
    }

    static LampDetailsGetModelResult^ CreateSuccessResult(_In_ uint32 value)
    {
        auto result = ref new LampDetailsGetModelResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        result->Model = value;
        result->m_creationContext = Concurrency::task_continuation_context::use_current();
        return result;
    }

    static LampDetailsGetModelResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new LampDetailsGetModelResult();
        result->Status = status;
        return result;
    }
internal:
    Concurrency::task_continuation_context m_creationContext = Concurrency::task_continuation_context::use_default();

private:
    int32 m_status;
    uint32 m_value;
};

public ref class LampDetailsGetTypeResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    property uint32 Type
    {
        uint32 get() { return m_value; }
    internal:
        void set(_In_ uint32 value) { m_value = value; }
    }

    static LampDetailsGetTypeResult^ CreateSuccessResult(_In_ uint32 value)
    {
        auto result = ref new LampDetailsGetTypeResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        result->Type = value;
        result->m_creationContext = Concurrency::task_continuation_context::use_current();
        return result;
    }

    static LampDetailsGetTypeResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new LampDetailsGetTypeResult();
        result->Status = status;
        return result;
    }
internal:
    Concurrency::task_continuation_context m_creationContext = Concurrency::task_continuation_context::use_default();

private:
    int32 m_status;
    uint32 m_value;
};

public ref class LampDetailsGetLampTypeResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    property uint32 LampType
    {
        uint32 get() { return m_value; }
    internal:
        void set(_In_ uint32 value) { m_value = value; }
    }

    static LampDetailsGetLampTypeResult^ CreateSuccessResult(_In_ uint32 value)
    {
        auto result = ref new LampDetailsGetLampTypeResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        result->LampType = value;
        result->m_creationContext = Concurrency::task_continuation_context::use_current();
        return result;
    }

    static LampDetailsGetLampTypeResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new LampDetailsGetLampTypeResult();
        result->Status = status;
        return result;
    }
internal:
    Concurrency::task_continuation_context m_creationContext = Concurrency::task_continuation_context::use_default();

private:
    int32 m_status;
    uint32 m_value;
};

public ref class LampDetailsGetLampBaseTypeResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    property uint32 LampBaseType
    {
        uint32 get() { return m_value; }
    internal:
        void set(_In_ uint32 value) { m_value = value; }
    }

    static LampDetailsGetLampBaseTypeResult^ CreateSuccessResult(_In_ uint32 value)
    {
        auto result = ref new LampDetailsGetLampBaseTypeResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        result->LampBaseType = value;
        result->m_creationContext = Concurrency::task_continuation_context::use_current();
        return result;
    }

    static LampDetailsGetLampBaseTypeResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new LampDetailsGetLampBaseTypeResult();
        result->Status = status;
        return result;
    }
internal:
    Concurrency::task_continuation_context m_creationContext = Concurrency::task_continuation_context::use_default();

private:
    int32 m_status;
    uint32 m_value;
};

public ref class LampDetailsGetLampBeamAngleResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    property uint32 LampBeamAngle
    {
        uint32 get() { return m_value; }
    internal:
        void set(_In_ uint32 value) { m_value = value; }
    }

    static LampDetailsGetLampBeamAngleResult^ CreateSuccessResult(_In_ uint32 value)
    {
        auto result = ref new LampDetailsGetLampBeamAngleResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        result->LampBeamAngle = value;
        result->m_creationContext = Concurrency::task_continuation_context::use_current();
        return result;
    }

    static LampDetailsGetLampBeamAngleResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new LampDetailsGetLampBeamAngleResult();
        result->Status = status;
        return result;
    }
internal:
    Concurrency::task_continuation_context m_creationContext = Concurrency::task_continuation_context::use_default();

private:
    int32 m_status;
    uint32 m_value;
};

public ref class LampDetailsGetDimmableResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    property bool Dimmable
    {
        bool get() { return m_value; }
    internal:
        void set(_In_ bool value) { m_value = value; }
    }

    static LampDetailsGetDimmableResult^ CreateSuccessResult(_In_ bool value)
    {
        auto result = ref new LampDetailsGetDimmableResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        result->Dimmable = value;
        result->m_creationContext = Concurrency::task_continuation_context::use_current();
        return result;
    }

    static LampDetailsGetDimmableResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new LampDetailsGetDimmableResult();
        result->Status = status;
        return result;
    }
internal:
    Concurrency::task_continuation_context m_creationContext = Concurrency::task_continuation_context::use_default();

private:
    int32 m_status;
    bool m_value;
};

public ref class LampDetailsGetColorResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    property bool Color
    {
        bool get() { return m_value; }
    internal:
        void set(_In_ bool value) { m_value = value; }
    }

    static LampDetailsGetColorResult^ CreateSuccessResult(_In_ bool value)
    {
        auto result = ref new LampDetailsGetColorResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        result->Color = value;
        result->m_creationContext = Concurrency::task_continuation_context::use_current();
        return result;
    }

    static LampDetailsGetColorResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new LampDetailsGetColorResult();
        result->Status = status;
        return result;
    }
internal:
    Concurrency::task_continuation_context m_creationContext = Concurrency::task_continuation_context::use_default();

private:
    int32 m_status;
    bool m_value;
};

public ref class LampDetailsGetVariableColorTempResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    property bool VariableColorTemp
    {
        bool get() { return m_value; }
    internal:
        void set(_In_ bool value) { m_value = value; }
    }

    static LampDetailsGetVariableColorTempResult^ CreateSuccessResult(_In_ bool value)
    {
        auto result = ref new LampDetailsGetVariableColorTempResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        result->VariableColorTemp = value;
        result->m_creationContext = Concurrency::task_continuation_context::use_current();
        return result;
    }

    static LampDetailsGetVariableColorTempResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new LampDetailsGetVariableColorTempResult();
        result->Status = status;
        return result;
    }
internal:
    Concurrency::task_continuation_context m_creationContext = Concurrency::task_continuation_context::use_default();

private:
    int32 m_status;
    bool m_value;
};

public ref class LampDetailsGetHasEffectsResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    property bool HasEffects
    {
        bool get() { return m_value; }
    internal:
        void set(_In_ bool value) { m_value = value; }
    }

    static LampDetailsGetHasEffectsResult^ CreateSuccessResult(_In_ bool value)
    {
        auto result = ref new LampDetailsGetHasEffectsResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        result->HasEffects = value;
        result->m_creationContext = Concurrency::task_continuation_context::use_current();
        return result;
    }

    static LampDetailsGetHasEffectsResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new LampDetailsGetHasEffectsResult();
        result->Status = status;
        return result;
    }
internal:
    Concurrency::task_continuation_context m_creationContext = Concurrency::task_continuation_context::use_default();

private:
    int32 m_status;
    bool m_value;
};

public ref class LampDetailsGetMinVoltageResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    property uint32 MinVoltage
    {
        uint32 get() { return m_value; }
    internal:
        void set(_In_ uint32 value) { m_value = value; }
    }

    static LampDetailsGetMinVoltageResult^ CreateSuccessResult(_In_ uint32 value)
    {
        auto result = ref new LampDetailsGetMinVoltageResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        result->MinVoltage = value;
        result->m_creationContext = Concurrency::task_continuation_context::use_current();
        return result;
    }

    static LampDetailsGetMinVoltageResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new LampDetailsGetMinVoltageResult();
        result->Status = status;
        return result;
    }
internal:
    Concurrency::task_continuation_context m_creationContext = Concurrency::task_continuation_context::use_default();

private:
    int32 m_status;
    uint32 m_value;
};

public ref class LampDetailsGetMaxVoltageResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    property uint32 MaxVoltage
    {
        uint32 get() { return m_value; }
    internal:
        void set(_In_ uint32 value) { m_value = value; }
    }

    static LampDetailsGetMaxVoltageResult^ CreateSuccessResult(_In_ uint32 value)
    {
        auto result = ref new LampDetailsGetMaxVoltageResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        result->MaxVoltage = value;
        result->m_creationContext = Concurrency::task_continuation_context::use_current();
        return result;
    }

    static LampDetailsGetMaxVoltageResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new LampDetailsGetMaxVoltageResult();
        result->Status = status;
        return result;
    }
internal:
    Concurrency::task_continuation_context m_creationContext = Concurrency::task_continuation_context::use_default();

private:
    int32 m_status;
    uint32 m_value;
};

public ref class LampDetailsGetWattageResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    property uint32 Wattage
    {
        uint32 get() { return m_value; }
    internal:
        void set(_In_ uint32 value) { m_value = value; }
    }

    static LampDetailsGetWattageResult^ CreateSuccessResult(_In_ uint32 value)
    {
        auto result = ref new LampDetailsGetWattageResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        result->Wattage = value;
        result->m_creationContext = Concurrency::task_continuation_context::use_current();
        return result;
    }

    static LampDetailsGetWattageResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new LampDetailsGetWattageResult();
        result->Status = status;
        return result;
    }
internal:
    Concurrency::task_continuation_context m_creationContext = Concurrency::task_continuation_context::use_default();

private:
    int32 m_status;
    uint32 m_value;
};

public ref class LampDetailsGetIncandescentEquivalentResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    property uint32 IncandescentEquivalent
    {
        uint32 get() { return m_value; }
    internal:
        void set(_In_ uint32 value) { m_value = value; }
    }

    static LampDetailsGetIncandescentEquivalentResult^ CreateSuccessResult(_In_ uint32 value)
    {
        auto result = ref new LampDetailsGetIncandescentEquivalentResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        result->IncandescentEquivalent = value;
        result->m_creationContext = Concurrency::task_continuation_context::use_current();
        return result;
    }

    static LampDetailsGetIncandescentEquivalentResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new LampDetailsGetIncandescentEquivalentResult();
        result->Status = status;
        return result;
    }
internal:
    Concurrency::task_continuation_context m_creationContext = Concurrency::task_continuation_context::use_default();

private:
    int32 m_status;
    uint32 m_value;
};

public ref class LampDetailsGetMaxLumensResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    property uint32 MaxLumens
    {
        uint32 get() { return m_value; }
    internal:
        void set(_In_ uint32 value) { m_value = value; }
    }

    static LampDetailsGetMaxLumensResult^ CreateSuccessResult(_In_ uint32 value)
    {
        auto result = ref new LampDetailsGetMaxLumensResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        result->MaxLumens = value;
        result->m_creationContext = Concurrency::task_continuation_context::use_current();
        return result;
    }

    static LampDetailsGetMaxLumensResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new LampDetailsGetMaxLumensResult();
        result->Status = status;
        return result;
    }
internal:
    Concurrency::task_continuation_context m_creationContext = Concurrency::task_continuation_context::use_default();

private:
    int32 m_status;
    uint32 m_value;
};

public ref class LampDetailsGetMinTemperatureResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    property uint32 MinTemperature
    {
        uint32 get() { return m_value; }
    internal:
        void set(_In_ uint32 value) { m_value = value; }
    }

    static LampDetailsGetMinTemperatureResult^ CreateSuccessResult(_In_ uint32 value)
    {
        auto result = ref new LampDetailsGetMinTemperatureResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        result->MinTemperature = value;
        result->m_creationContext = Concurrency::task_continuation_context::use_current();
        return result;
    }

    static LampDetailsGetMinTemperatureResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new LampDetailsGetMinTemperatureResult();
        result->Status = status;
        return result;
    }
internal:
    Concurrency::task_continuation_context m_creationContext = Concurrency::task_continuation_context::use_default();

private:
    int32 m_status;
    uint32 m_value;
};

public ref class LampDetailsGetMaxTemperatureResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    property uint32 MaxTemperature
    {
        uint32 get() { return m_value; }
    internal:
        void set(_In_ uint32 value) { m_value = value; }
    }

    static LampDetailsGetMaxTemperatureResult^ CreateSuccessResult(_In_ uint32 value)
    {
        auto result = ref new LampDetailsGetMaxTemperatureResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        result->MaxTemperature = value;
        result->m_creationContext = Concurrency::task_continuation_context::use_current();
        return result;
    }

    static LampDetailsGetMaxTemperatureResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new LampDetailsGetMaxTemperatureResult();
        result->Status = status;
        return result;
    }
internal:
    Concurrency::task_continuation_context m_creationContext = Concurrency::task_continuation_context::use_default();

private:
    int32 m_status;
    uint32 m_value;
};

public ref class LampDetailsGetColorRenderingIndexResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    property uint32 ColorRenderingIndex
    {
        uint32 get() { return m_value; }
    internal:
        void set(_In_ uint32 value) { m_value = value; }
    }

    static LampDetailsGetColorRenderingIndexResult^ CreateSuccessResult(_In_ uint32 value)
    {
        auto result = ref new LampDetailsGetColorRenderingIndexResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        result->ColorRenderingIndex = value;
        result->m_creationContext = Concurrency::task_continuation_context::use_current();
        return result;
    }

    static LampDetailsGetColorRenderingIndexResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new LampDetailsGetColorRenderingIndexResult();
        result->Status = status;
        return result;
    }
internal:
    Concurrency::task_continuation_context m_creationContext = Concurrency::task_continuation_context::use_default();

private:
    int32 m_status;
    uint32 m_value;
};

public ref class LampDetailsGetLampIDResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    property Platform::String^ LampID
    {
        Platform::String^ get() { return m_value; }
    internal:
        void set(_In_ Platform::String^ value) { m_value = value; }
    }

    static LampDetailsGetLampIDResult^ CreateSuccessResult(_In_ Platform::String^ value)
    {
        auto result = ref new LampDetailsGetLampIDResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        result->LampID = value;
        result->m_creationContext = Concurrency::task_continuation_context::use_current();
        return result;
    }

    static LampDetailsGetLampIDResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new LampDetailsGetLampIDResult();
        result->Status = status;
        return result;
    }
internal:
    Concurrency::task_continuation_context m_creationContext = Concurrency::task_continuation_context::use_default();

private:
    int32 m_status;
    Platform::String^ m_value;
};

} } } } 
