//-----------------------------------------------------------------------------
// <auto-generated> 
//   This code was generated by a tool. 
// 
//   Changes to this file may cause incorrect behavior and will be lost if  
//   the code is regenerated.
//
//   Tool: AllJoynCodeGenerator.exe
//
//   This tool is located in the Windows 10 SDK and the Windows 10 AllJoyn 
//   Visual Studio Extension in the Visual Studio Gallery.  
//
//   The generated code should be packaged in a Windows 10 C++/CX Runtime  
//   Component which can be consumed in any UWP-supported language using 
//   APIs that are available in Windows.Devices.AllJoyn.
//
//   Using AllJoynCodeGenerator - Invoke the following command with a valid 
//   Introspection XML file and a writable output directory:
//     AllJoynCodeGenerator -i <INPUT XML FILE> -o <OUTPUT DIRECTORY>
// </auto-generated>
//-----------------------------------------------------------------------------
#pragma once

using namespace concurrency;

namespace org { namespace allseen { namespace LSF { namespace LampState {

ref class LampStateConsumer;

public ref class LampStateTransitionLampStateResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    property uint32 LampResponseCode
    {
        uint32 get() { return m_interfaceMemberLampResponseCode; }
    internal:
        void set(_In_ uint32 value) { m_interfaceMemberLampResponseCode = value; }
    }
    
    static LampStateTransitionLampStateResult^ CreateSuccessResult(_In_ uint32 interfaceMemberLampResponseCode)
    {
        auto result = ref new LampStateTransitionLampStateResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        result->LampResponseCode = interfaceMemberLampResponseCode;
        result->m_creationContext = Concurrency::task_continuation_context::use_current();
        return result;
    }
    
    static LampStateTransitionLampStateResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new LampStateTransitionLampStateResult();
        result->Status = status;
        return result;
    }
internal:
    Concurrency::task_continuation_context m_creationContext = Concurrency::task_continuation_context::use_default();

private:
    int32 m_status;
    uint32 m_interfaceMemberLampResponseCode;
};

public ref class LampStateApplyPulseEffectResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    property uint32 LampResponseCode
    {
        uint32 get() { return m_interfaceMemberLampResponseCode; }
    internal:
        void set(_In_ uint32 value) { m_interfaceMemberLampResponseCode = value; }
    }
    
    static LampStateApplyPulseEffectResult^ CreateSuccessResult(_In_ uint32 interfaceMemberLampResponseCode)
    {
        auto result = ref new LampStateApplyPulseEffectResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        result->LampResponseCode = interfaceMemberLampResponseCode;
        result->m_creationContext = Concurrency::task_continuation_context::use_current();
        return result;
    }
    
    static LampStateApplyPulseEffectResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new LampStateApplyPulseEffectResult();
        result->Status = status;
        return result;
    }
internal:
    Concurrency::task_continuation_context m_creationContext = Concurrency::task_continuation_context::use_default();

private:
    int32 m_status;
    uint32 m_interfaceMemberLampResponseCode;
};

public ref class LampStateJoinSessionResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    property LampStateConsumer^ Consumer
    {
        LampStateConsumer^ get() { return m_consumer; }
    internal:
        void set(_In_ LampStateConsumer^ value) { m_consumer = value; }
    };

private:
    int32 m_status;
    LampStateConsumer^ m_consumer;
};

public ref class LampStateGetVersionResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    property uint32 Version
    {
        uint32 get() { return m_value; }
    internal:
        void set(_In_ uint32 value) { m_value = value; }
    }

    static LampStateGetVersionResult^ CreateSuccessResult(_In_ uint32 value)
    {
        auto result = ref new LampStateGetVersionResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        result->Version = value;
        result->m_creationContext = Concurrency::task_continuation_context::use_current();
        return result;
    }

    static LampStateGetVersionResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new LampStateGetVersionResult();
        result->Status = status;
        return result;
    }
internal:
    Concurrency::task_continuation_context m_creationContext = Concurrency::task_continuation_context::use_default();

private:
    int32 m_status;
    uint32 m_value;
};

public ref class LampStateGetOnOffResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    property bool OnOff
    {
        bool get() { return m_value; }
    internal:
        void set(_In_ bool value) { m_value = value; }
    }

    static LampStateGetOnOffResult^ CreateSuccessResult(_In_ bool value)
    {
        auto result = ref new LampStateGetOnOffResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        result->OnOff = value;
        result->m_creationContext = Concurrency::task_continuation_context::use_current();
        return result;
    }

    static LampStateGetOnOffResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new LampStateGetOnOffResult();
        result->Status = status;
        return result;
    }
internal:
    Concurrency::task_continuation_context m_creationContext = Concurrency::task_continuation_context::use_default();

private:
    int32 m_status;
    bool m_value;
};

public ref class LampStateSetOnOffResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    static LampStateSetOnOffResult^ CreateSuccessResult()
    {
        auto result = ref new LampStateSetOnOffResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        result->m_creationContext = Concurrency::task_continuation_context::use_current();
        return result;
    }

    static LampStateSetOnOffResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new LampStateSetOnOffResult();
        result->Status = status;
        return result;
    }
internal:
    Concurrency::task_continuation_context m_creationContext = Concurrency::task_continuation_context::use_default();

private:
    int32 m_status;
};

public ref class LampStateGetHueResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    property uint32 Hue
    {
        uint32 get() { return m_value; }
    internal:
        void set(_In_ uint32 value) { m_value = value; }
    }

    static LampStateGetHueResult^ CreateSuccessResult(_In_ uint32 value)
    {
        auto result = ref new LampStateGetHueResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        result->Hue = value;
        result->m_creationContext = Concurrency::task_continuation_context::use_current();
        return result;
    }

    static LampStateGetHueResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new LampStateGetHueResult();
        result->Status = status;
        return result;
    }
internal:
    Concurrency::task_continuation_context m_creationContext = Concurrency::task_continuation_context::use_default();

private:
    int32 m_status;
    uint32 m_value;
};

public ref class LampStateSetHueResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    static LampStateSetHueResult^ CreateSuccessResult()
    {
        auto result = ref new LampStateSetHueResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        result->m_creationContext = Concurrency::task_continuation_context::use_current();
        return result;
    }

    static LampStateSetHueResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new LampStateSetHueResult();
        result->Status = status;
        return result;
    }
internal:
    Concurrency::task_continuation_context m_creationContext = Concurrency::task_continuation_context::use_default();

private:
    int32 m_status;
};

public ref class LampStateGetSaturationResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    property uint32 Saturation
    {
        uint32 get() { return m_value; }
    internal:
        void set(_In_ uint32 value) { m_value = value; }
    }

    static LampStateGetSaturationResult^ CreateSuccessResult(_In_ uint32 value)
    {
        auto result = ref new LampStateGetSaturationResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        result->Saturation = value;
        result->m_creationContext = Concurrency::task_continuation_context::use_current();
        return result;
    }

    static LampStateGetSaturationResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new LampStateGetSaturationResult();
        result->Status = status;
        return result;
    }
internal:
    Concurrency::task_continuation_context m_creationContext = Concurrency::task_continuation_context::use_default();

private:
    int32 m_status;
    uint32 m_value;
};

public ref class LampStateSetSaturationResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    static LampStateSetSaturationResult^ CreateSuccessResult()
    {
        auto result = ref new LampStateSetSaturationResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        result->m_creationContext = Concurrency::task_continuation_context::use_current();
        return result;
    }

    static LampStateSetSaturationResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new LampStateSetSaturationResult();
        result->Status = status;
        return result;
    }
internal:
    Concurrency::task_continuation_context m_creationContext = Concurrency::task_continuation_context::use_default();

private:
    int32 m_status;
};

public ref class LampStateGetColorTempResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    property uint32 ColorTemp
    {
        uint32 get() { return m_value; }
    internal:
        void set(_In_ uint32 value) { m_value = value; }
    }

    static LampStateGetColorTempResult^ CreateSuccessResult(_In_ uint32 value)
    {
        auto result = ref new LampStateGetColorTempResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        result->ColorTemp = value;
        result->m_creationContext = Concurrency::task_continuation_context::use_current();
        return result;
    }

    static LampStateGetColorTempResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new LampStateGetColorTempResult();
        result->Status = status;
        return result;
    }
internal:
    Concurrency::task_continuation_context m_creationContext = Concurrency::task_continuation_context::use_default();

private:
    int32 m_status;
    uint32 m_value;
};

public ref class LampStateSetColorTempResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    static LampStateSetColorTempResult^ CreateSuccessResult()
    {
        auto result = ref new LampStateSetColorTempResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        result->m_creationContext = Concurrency::task_continuation_context::use_current();
        return result;
    }

    static LampStateSetColorTempResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new LampStateSetColorTempResult();
        result->Status = status;
        return result;
    }
internal:
    Concurrency::task_continuation_context m_creationContext = Concurrency::task_continuation_context::use_default();

private:
    int32 m_status;
};

public ref class LampStateGetBrightnessResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    property uint32 Brightness
    {
        uint32 get() { return m_value; }
    internal:
        void set(_In_ uint32 value) { m_value = value; }
    }

    static LampStateGetBrightnessResult^ CreateSuccessResult(_In_ uint32 value)
    {
        auto result = ref new LampStateGetBrightnessResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        result->Brightness = value;
        result->m_creationContext = Concurrency::task_continuation_context::use_current();
        return result;
    }

    static LampStateGetBrightnessResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new LampStateGetBrightnessResult();
        result->Status = status;
        return result;
    }
internal:
    Concurrency::task_continuation_context m_creationContext = Concurrency::task_continuation_context::use_default();

private:
    int32 m_status;
    uint32 m_value;
};

public ref class LampStateSetBrightnessResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    static LampStateSetBrightnessResult^ CreateSuccessResult()
    {
        auto result = ref new LampStateSetBrightnessResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        result->m_creationContext = Concurrency::task_continuation_context::use_current();
        return result;
    }

    static LampStateSetBrightnessResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new LampStateSetBrightnessResult();
        result->Status = status;
        return result;
    }
internal:
    Concurrency::task_continuation_context m_creationContext = Concurrency::task_continuation_context::use_default();

private:
    int32 m_status;
};

} } } } 
